### ISSUE TITLE
Collaborator Request

### ISSUE THREAD

**Issue by Neur0plasticity** [fastify/help#115]
Hi,

I love node.js as a first choice server.
Been developing on it 4 years.

My true niche is software optimization engineering.
Written plenty of algorithms with phenomenal before/after benchmarks.

Besides handcrafting an esoteric high performant algorithm, I've picked up many tricks tweaking
node.js that are 2nd nature by now.

Is it cool If i join yall?

**Comment by StarpTech** [comment]
Hi @Neur0plasticity,
in order to be considered as a collaborator, you have to make significant and valuable contributions to the fastify ecosystem. In that process, we know you better and it will help answer that question.

Feel free to pick some [Good first issues](https://github.com/fastify/fastify/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) and create a PR. We will help you at delivering your code.
