### ISSUE TITLE
How to "attach" a websocket api to an existing api?

### ISSUE THREAD

**Issue by Extarys** [fastify/help#130]
## 💬 Questions and Help
Is there a way I could use websocket to attach to an api within fastify? 

My websocket connection is made to `localhost:3000/api/ws`. I'm thinking about using events to redirect to specific api paths:

Example:
```
socket.on('/v1/user/image', (msg) => {
    // Redirect to v1/user/image route
    socket.send(msg)
})
```

Since I expect clients to do 20 queries per minutes, I'd like to allow the api to also accept websocket, but use the same routes, if that make sense. I'd use the HTTP api as fallback on the client-side if ws is not supported. I also would like to avoid maintaining two different apis (websocket and http/s). How do people usually manage that?

**Comment by Eomm** [comment]
Sorry, I don't completely understand what you want to do, but for sure maintaining two apis could be an issue if they should do the same thing.

Did you check [fastify-websocket](https://github.com/fastify/fastify-websocket) already?

I think you can archive your needs writing the business logic without reference to request/response in order to adapt the HTTP api and WS one

**Comment by Extarys** [comment]
@Eomm thanks for your reply. I didn't think about reworking my api to exlcude req/res and make it "hybrid", good idea.

I installed it and playing with the config. I'm using `fastify-tls-keygen` to test https. Is this plugin compatible with `wss`? I couldn't find much on it and I never used it (didn't know there was a secure websocket protocol)
