### ISSUE TITLE
Why can't we `prefix` when using `fastify-plugin`?

### ISSUE THREAD

**Issue by jsumners** [fastify/help#174]
It's well documented (e.g. https://www.fastify.io/docs/v2.13.x/Routes/#route-prefixing) that `fastify.register(plugin, { prefix: '/v1' })` will not apply the prefix if `plugin` is wrapped by `fastify-plugin`. But why? Can't we internally do the equivalent of:

```js
function register (plugin, options, done) {
  if (options.prefix && plugin.wrapped) {
    return this.register((instance, opts, done2) => {
      instance.register(plugin, options, done)
    })
  }
  // do it normally
}
```

**Comment by mcollina** [comment]
fastify-plugin skips override which sets https://github.com/fastify/fastify/blob/64296c84b57eb8f6f63bf51579febcfd274a97a5/fastify.js#L471.

Note that we cannot do this because fastify-plugins skips the encapsulation, which allows us to change that value.

It's _likely_ possible to be able to set it anyway if we override and restore that value after the current plugin has loaded. This is going to be complex. Would you like to give it a shot? I think it would be helpful.

The technique I've been using to deal with this is to wrap a plugin in a plugin (see https://github.com/mcollina/fastify-gql/blob/ff90e03e5c2aaf59000e56197a2051238454e962/index.js#L113-L123), so I never needed to implement this. Possibly this should be documented.

**Comment by jsumners** [comment]
> The technique I've been using to deal with this is to wrap a plugin in a plugin

Right. That's what I'm suggesting be done internally so that this is more developer friendly. 

I'll try to get to it, but I am SUPER busy right now.

**Comment by mcollina** [comment]
The technique works because the routes and the decorators are applied to 2 separate plugins at different encapsulation levels. (root) -> decorators (non-encapsulated) -> routes (encapsulated).

**Comment by jsumners** [comment]
This will require some thought, for sure. But I think it could improve developer experience. Coming back to baseline Fastify after a while of wrapping it, this was a surprise for me. Basically, I forgot about this, essentially obscure, rule/detail.
