### ISSUE TITLE
Lacking documentation clarity in error serialization

### ISSUE THREAD

**Issue by alexzherdev** [fastify/help#214]
#### You have already researched for similiar issues?
Yes

#### What are you trying to achieve or the steps to reproduce?
The interplay between various hooks and the custom error handler isn't well documented as far as I can see. In particular, I'm using a `preSerialization` hook to enforce JSON:API format. I'm also using a custom error handler with `setErrorHandler`.

```js
app.addHook('preSerialization', async (req, reply, payload) => {
  return serializer.serialize('items', payload);
});

app.setErrorHandler(async (error, req, reply) => {
  // sending error to airbrake
  // as well as some logic like the following
  if (error instanceof SomeError) {
    throw new SomeOtherError();
  }
  throw error;
});
```

#### What was the result you received?
When I throw or return an error object from the error handler, it doesn't go through `preSerialization`. I thought I could, instead of throwing, serialize the error right in the handler like
```js
app.setErrorHandler(async (error, req, reply) => {
  // [...]
  return serializer.serializeError(error);
});
```
but then `preSerialization` starts getting invoked on top of `serializeError` result which produces an incorrect payload. What I landed on is (using `reply.send` because I also want to set the content type):

```js
app.setErrorHandler(async (error, req, reply) => {
  [...]
  reply.type('application/json').send(JSON.stringify(serializer.serializeError(error)));
});
```

Then `preSerialization` is not invoked since the payload is a string. But I'm wondering if this is the right way.

#### What did you expect?

Ultimately, I'd like to see more information in the docs regarding how the custom error handler affects the hooks and really, how it fits into the lifecycle. E.g., it was unexpected that I could return an object from the error handler and have it be serialized as though it was a regular response payload.
In addition, this bit in `preSerialization` doesn't seem fully correct? (It seems not to be called if payload is an `Error` as well)
> Note: the hook is NOT called if the payload is a string, a Buffer, a stream or null.

#### Context

* *node version*: 12.16.1
* *fastify version*: 2.12.1
* *os*: macOS 10.14.6
* *any other relevant information*:

**Comment by mcollina** [comment]
I think this use case of `reply.serialize` is not fully covered by Fastify or out tests. __This definitely needs some docs update__. Would you like to send a PR?

Docs aside, how would you improve this feature? I think we could do much better here.

**Comment by admataz** [comment]
@alexzherdev: 

With a view to improving docs and the error handling, I've been looking at this issue - I'd appreciate if you have any feedback on these notes: 

### Understanding Errors in Fastify lifecycle hooks and custom error handler

From the [docs](https://www.fastify.io/docs/latest/Hooks/#manage-errors-from-a-hook): 
> If you get an error during the execution of your hook, just pass it to `done()` and Fastify will automatically close the request and send the appropriate error code to the user.

If you have defined a custom error handler for using `setErrorHandler` the error will  be routed there, otherwise it will be routed to fastify’s generic error handler. 

Some things to consider in your custom error handler: 

- you can `reply.send(data)`  which will be behave as it would be in [regular route handlers](https://www.fastify.io/docs/latest/Reply/#senddata)
	- objects are serialised (triggering the `preSerialization` lifecycle hook, if you have one defined
	- strings, buffers, streams are sent to the client, with appropriate headers (no serialization)
	- errors (new error or  the received error parameter re-thrown)  - will trigger the `onError` lifecycle hook, and send the error to the user
	- an error will not be triggered twice from a lifecycle hook - fastify internally monitors the error invocation to avoid infinite loops for errors thrown in the reply phases of the lifecycle. (those after the route handler) 

In your initial case,  when you are returning/ throwing/ sending the error object from your custom error handler - fastify is  detecting it as an error, and returning it in the reply as expected. 

In your second instance,  I’m not sure what `serializeError` does, but it looks like it returns an `object` (as opposed to a serialised object as a string or an actual error instance)  - so according the rules of `reply.send()` this is then a candidate for `preSerialization` and serialized for the payload to be sent as the response.  

Your workaround - to `serialialize`  and `stringify` in the error handler works - because as you say, it returns a `string`.  But you may want to think instead about returning an `object` from the custom error handler, and conditionally handling the serialization of these error objects within the `preSerialization` hook. 

I think documentation wise -  some explanation in the [`server.setErrorHandler` documentation](https://www.fastify.io/docs/latest/Server/#seterrorhandler) that it is the `reply.send(data)`  behaviour - as I have outlined above would help? 

In terms of potential improvements,  offering more granular route-level error handlers with specific output schema is something that is being discussed  - would that be useful? 

Thanks
