### ISSUE TITLE
can we rewrite configValidator.js, reply.js, request.js in source code with modern syntax?

### ISSUE THREAD

**Issue by anlexN** [fastify/help#293]
#### Context

* *node version*: all
* *fastify version*: all
* *os*: Mac, Windows
* *any other relevant information*:
now it is very complex and painful to review.

**Comment by mcollina** [comment]
Thanks for your point of view! I think this type of discussion should be left to people that works on the code. Would you like to send a few PRs and contribute to the project? Then you'd have a say.

(Note that this is similar to somebody telling they do not like somebody else's house wall paint).

---

On a technical merit there are reasons to _most_ of the syntax used in Fastify. "Old" syntax has been in V8 longer and it has been heavily optimized. An example of this is the use of `var` instead of `let`. In Node 8 and before (and early Node 10 releases), `let` was significantly slower than `var`. 

There are also constructs that are inherently faster. An example of this is the use of `for(;;)` instead of `for..of`. Those are a no-go.

If you (or anybody else) care about specific syntax changes, open an issue and propose them one-by-one. We'll be happy to review and benchmark the various changes.

(One change that can be worked on is migrating from var to let).

**Comment by anlexN** [comment]
i think syntax performance should be js engine thing, not our developer thing. and i strive to follow ecmascript standard. and fresh student mostly can not master old style syntax so that can not understand fastify source code. i am willing to contribute, but you want a good benchmark score, i think my effort is no meaning.
so good benchmark score is very important??? or say ecmascript standard is not good???

**Comment by mcollina** [comment]
Thanks for your feedback - I think my answer was throughout and I have nothing more to add.
