### ISSUE TITLE
Pass variable from origin function

### ISSUE THREAD

**Issue by samevision** [fastify/help#295]
Hello guys,

I try to use fastify-cors dynamically. So each request runs through my origin function that checks if the origin is available in the database. 

```
origin: async (origin, cb) => {
    const license = await getLicense(origin)
    if (license) {
      cb(null, true)
      return
    } else {
      cb(null, false)
    }
  }
```

Two problems occur:

1. How am I able to pass the license object to the requested function? I think it is unnecessary to grab the license data twice.

2. I receive an error "Reply already sent" since I am using async await. How can I solve this?

Thanks for your help

Best

**Comment by Ethan-Arrowood** [comment]
Can you expand your code a bit? Maybe something we could run locally? That'll help me understand your questions better. Thank you!

**Comment by samevision** [comment]
Thanks for your reply.

When my app receives a post request it runs through fastify-cors:

app.js
```
fastify.register(require('fastify-cors'), {
  origin: (origin, cb) => {
    getLicense(origin).then(license => {
      if (license) {
        cb(null, true)
        return
      } else {
        cb(null, false)
      }
    })
  },
  methods: ['POST']
})
```

getLicense() checks if the origin has a license:
```
const url = origin.replace("http://", "").replace("https://", "").replace("www.", "").replace("/", "")

const license = await models.License.findOne({
	where: {
		url: url
	}
})

return license
```

Since I have to access the license object inside of the function that is requested by post I don't want to query it again. I want to pass the license object to my function.

**Comment by Eomm** [comment]
> I receive an error "Reply already sent" since I am using async await. How can I solve this?

I think, as you did, that was caused by the use of the `origin` function that was `ascyn` and it was using the `callback` too.

> How am I able to pass the license object to the requested function? I think it is unnecessary to grab the license data twice.

Right now this is not possible out-of the box since the request object is not exposed to that function. You can do but it would be very tricky and not maintainable for an application.

I would implement this behaviour in an `onRequest` hook since it is an auth validation. In a hook, you can access the `request` object and attach the info to its context.
I would use a prefetch on the DB on application start to load the valid origins that the cors plugin will use, so it would be a sync function too.

**Comment by samevision** [comment]
Thanks for your response.

I set fastify-cors settings "origin: true" and I created a onRequest hook:
```
fastify.addHook('onRequest', (req, res, next) => {
  getLicense(req.headers.origin).then(license => {
    if (license) {
      req.license = license
      next()
    } else {
      return
    }
  })
})
```

That works fine and I can use the license object. Is that best practice in terms of security and performance?

**Comment by Eomm** [comment]
> Is that best practice in terms of security and performance?

Regarding the security I can't say anything since I don't know your setup like:
- cors acts before of after your hook?
- do you have auth?
- etc..

I can notice only that the `getLicense` function must be aware of the user input

> Is that best practice 

I think yes, hooks are made of this!
I would add some caching like a LRU since I assume the origin should not change so often
