### ISSUE TITLE
You need to explain things more

### ISSUE THREAD

**Issue by hs-dev-web** [fastify/help#441]
in this section you said:

https://www.fastify.io/docs/latest/Validation-and-Serialization/#serializer-compiler

> You must provide a function to serialize every route where you have defined a response JSON Schema.

Why? I need more explanation to understand WHY?

while in this section you said:

https://www.fastify.io/docs/latest/Validation-and-Serialization/#serialization

> We encourage you to use an output schema, as it can drastically increase throughput and help prevent accidental disclosure of sensitive information.

========================================================

If I have this data:

`{ id: 1, name: 'Foo', image: 'BIG IMAGE' }`

and this shcema:

`response: {
      '2xx': {
        id: { type: 'number' },
        name: { type: 'string' }
      }
}`

by implementing the first section I mentioned above, the output is:

`{"id":1,"name":"Foo","image":"BIG IMAGE"}`

image is included in the output result regardless the schema.

it seems contradict your saying in the second section I mentioned above.

### as it can drastically increase throughput and help prevent accidental disclosure of sensitive information.

**Comment by evanshortiss** [comment]
I believe this is a simple documentation mistake, but will let more knowledgeable people correct me if necessary 😀

The line[1] a little misleading, since fastify uses a default serialiser, as mentioned in the paragraph above[2]. 

Good PR opportunity perhaps?

[1] `You must provide a function to serialize every route where you have defined a response JSON Schema.`

[2] `Usually, you will send your data to the clients as JSON, and Fastify has a powerful tool to help you, fast-json-stringify, which is used if you have provided an output schema in the route options.`

**Comment by evanshortiss** [comment]
BTW, the reason `image` is included is because the example serialiser is simply running `JSON.stringify`, whereas the built-in serialiser applies the JSON schema.
