### ISSUE TITLE
Having data access as a plugin

### ISSUE THREAD

**Issue by cemremengu** [fastify/help#49]
I am just curious to know what people think about having data access layer as a plugin like:

```js
const fp = require('fastify-plugin');

function fetchAll() {
  return this.oracle.conn.execute('SELECT * FROM USERS');
}

module.exports = fp(async fastify => {
  fastify.decorate('userStore', { 
    fetchAll: fetchAll.bind(fastify),
    someOtherFunction: blah.bind(fastify)
  });
});
```

Do you think this is a good approach?

**Comment by Ethan-Arrowood** [comment]
I've battled with this before and would like to know the best approach as well. I sometimes think it depends on your app architecture.

If the server is accessing the database from the same auth source then you can probably keep an open database connection and exchange information through a global data access layer. 

If the server is accessing the database from different auth sources (like each client gets its own unique access to the database). Then its probably better to open the database connection per server instance and either 
  a. handle the data access through some general global layer that requires an initial authorization step
  b. handle data access through an non global layer and have it be instantiated within the client-server session instance

(sorry if my wording is vague or confusing. I struggle to describe this issue as I don't think I fully understand the issue or potential solutions yet)

**Comment by mcollina** [comment]
A couple of notes:

1. Use https://github.com/nearform/sql to generate SQL (or analogous). It's so much better.
2. I think having a "model" or "data access" layer can be both a blessing or a curse, and there is no silver bullet. I personally prefer to have none, and do direct data access in my routes. This reduces the amount of code I have to write, maintain and test. I tend to use a lot of utilities without states to support it, so that routes are indeed thin. I organize my routes logically in plugins, and I try to limit the number of common collections/tables between plugins. I rely on unit tests to know if I cross some streams. I think about a plugin containing routes as a microservice.
3. A full data access layer is very useful in extremely large monolithic applications. The problem for these is the overall architecture (do not build a monolith) and the full data access layer is just a code smell.
