### ISSUE TITLE
Basics of creating a middleware

### ISSUE THREAD

**Issue by Extarys** [fastify/help#50]
#### You have already researched for similiar issues?
Yes, this github and SO.

#### What are you trying to achieve or the steps to reproduce?

A small middleware that verify the api key in the database and throw a 429 too many requests if there was too many requests in a certain period.

My route:
```js
const ApiKey = require('../../middleware/ApiKey')
fastify.get('/myData', ApiKey(), function(req, reply) {

}
```
ApiKey
```js
module.exports = function (fastify, options, next) {
  fastify.addHook('onRequest', async (request, reply) => {
    // some code
    console.log(request)
    // error occurred
    if (err) {
      throw new Error('some errors occurred.')
    }
    return
  })
  next()
}
```

#### What was the result you received?
`TypeError: fastify.addHook is not a function`
or 
`next is not a function` if I remove the hook.

#### What did you expect?
Ability to see the request (query, path) and adjust the reply inside the middleware.

#### Context

* *node version*: 8.12.0
* *fastify version*: 2.0-rc4
* *os*: Linux Mint 19.1
* *any other relevant information*:

**Comment by delvedor** [comment]
The [routes declaration](https://www.fastify.io/docs/latest/Routes/) is different than express, if you want to add a [middleware](https://www.fastify.io/docs/latest/Middlewares/) you should use the `.use` API.

If you are writing your code from scratch, and you are not using an old Express implementation, you should use Fastify hooks, since Fastify middlewares are just a compatibility layer with Express.

Your example should be rewritten in this way:
```js
// index.js
fastify.register(require('./auth-hook'))
fastify.get('/myData', function(req, reply) {

}

// auth-hook.js
const fp = require('fastify-plugin')
module.exports = fp(function (fastify, options, next) {
  fastify.addHook('onRequest', async (request, reply) => {
    // some code
    console.log(request)
    // error occurred
    if (err) {
      throw new Error('some errors occurred.')
    }
    return
  })
  next()
})
```

I also suggest you to read our [plugins guide](https://www.fastify.io/docs/latest/Plugins-Guide/) :)

**Comment by Extarys** [comment]
Oh thanks @delvedor !

One small question. Is it possible to use a middleware for only one route?

My little api is already splited, but inside a route file I may have 2 or 3 paths where I don't want to use the middleware.

I cannot find in the doc how to make this happen. Should I make yet another file just for those? (The hierarchy is getting confusing XD)

**Comment by nwoltman** [comment]
@Extarys I think you're looking for the [`route level hooks` doc](https://www.fastify.io/docs/latest/Hooks/#route-level-hooks). That lets you set hooks on a single route.

Also, you're getting "err is not defined" because you're trying to access some variable called `err` but the variable isn't defined anywhere.

```js
module.exports = fp(function (fastify, options, next) {
  fastify.addHook('onRequest', async (request, reply) => {
    console.log(request)

    if (err) { // err hasn't been declared before this line (so it doesn't exist)
      throw new Error('some errors occurred.')
    }
  })
  next()
})
```

**Comment by delvedor** [comment]
If you want to run an hook just for one route you can wrap that route inside a plugin:
```js
// index.js
fastify.register(require('./auth-route'))

// auth-route.js
module.exports = function (fastify, options, next) {
  fastify.addHook('onRequest', async (request, reply) => {
    // some code
    console.log(request)
    // error occurred
    if (err) {
      throw new Error('some errors occurred.')
    }
    return
  })

  fastify.get('/myData', function(req, reply) {

  })
  next()
}
```

Otherwise, if you are using v2 you can use the other route declaration syntax:
```js
fastify.route({
  method: 'GET',
  url: '/',
  preValidation: async (request, reply) => {

  }
  handler: function(req, reply) {

  }
})
```

Regarding your last question, I suggest you to read our [hooks documentation](https://www.fastify.io/docs/latest/Hooks/) :)

**Comment by Extarys** [comment]
Thanks! <3
