### ISSUE TITLE
Async insert document and return return in fastify (FST_ERR_PROMISE_NOT_FULLFILLED)

### ISSUE THREAD

**Issue by Extarys** [fastify/help#52]
#### You have already researched for similiar issues?
Yes. No useful results for "FST_ERR_PROMISE_NOT_FULLFILLED"

#### What are you trying to achieve or the steps to reproduce?

I'm calling a remote api and insert the result in a db. The document is present in the DB but fastify doesn't receive the response from it.

I used to be able to use similar code without using promises.

```js
  fastify.get('/getCurrent', async function (request, reply) {
    console.log(request.query)

    let currentData = await thirdpartyapi(1123456)

    try {
      mybucket.insert(
        currentData
      ).then(async (body) => {
        console.log(body)
        await reply.send(body);
      })

    }
    catch(err) {
      reply.send(err);
    }

  })


  next()
}
```

#### What was the result you received?
`FastifyError","message":"FST_ERR_PROMISE_NOT_FULLFILLED: Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError [FST_ERR_PROMISE_NOT_FULLFILLED]: FST_ERR_PROMISE_NOT_FULLFILLED: Promise may not be fulfilled with 'undefined' when statusCode is not 204`

#### Context

* *node version*: 8.12
* *fastify version*: 2.0-rc4
* *os*: Mac, Windows... **Linux**

**Comment by nwoltman** [comment]
For `async` handlers, Fastify either expects the request body to be returned by the handler function, or it expects `reply.send()` to be called *before* the function returns.

By doing

```js
 mybucket.insert(
  currentData
).then(async (body) => { })
```

instead of

```js
const body = await mybucket.insert(currentData)
```

you're calling `reply.send()` inside the `.then()` function, which runs *after* the handler function returns.

You can also avoid using a `try-catch` by writing your handler function like this:

```js
fastify.get('/getCurrent', async function (request, reply) {
  console.log(request.query)

  const currentData = await thirdpartyapi(1123456)
  
  return mybucket.insert(currentData)
})
```

There's a section about this in the [documentation](https://www.fastify.io/docs/latest/Routes/#async-await).
