### ISSUE TITLE
Support Opensearch-js module

### ISSUE THREAD

**Issue by danliiii** [fastify/help#527]
Could you please help to create a new module for support opensearch-js

**Comment by climba03003** [comment]
I have check a little bit about `OpenSearch`.
https://developer.mozilla.org/en-US/docs/Web/OpenSearch

It is a `xml` content only and the search url and logic is decided by the developer. I do not think we can comes up a general structure for the `OpenSearch` because all the logic will be provided by the consumer.

I will let the others who interested in this field to make the plugin.

**Comment by kibertoad** [comment]
@danliiii Would you be interested in creating such plugin yourself? We would be happy to include it in a list of community plugins.

**Comment by is2ei** [comment]
I guess @danliiii means [opensearch-js](https://github.com/opensearch-project/opensearch-js) package.
