### ISSUE TITLE
Fastify validation custom status code.

### ISSUE THREAD

**Issue by MoSheikh** [fastify/help#588]
#### You have already researched for similar issues?
I did find [something very similar](https://github.com/fastify/fastify/issues/1586) but didn't see any answers that pertain to the status code aspect of things rather than the error message. 

#### What are you trying to achieve, or the steps to reproduce?
I'm trying understand whether it's currently possible to specify the status codes that get produced when fastify validates a request. After going through MDN docs and other public APIs, I've been thinking that a `422` code would be more suitable than `400` code in the case of a missing field for example. 

Thank you!

**Comment by simonplend** [comment]
The Fastify documentation for Validation has an error handling example where a status code is set within a `fastify.setErrorHandler` handler:

https://www.fastify.io/docs/latest/Reference/Validation-and-Serialization/#error-handling

I think that should help with what you're trying to achieve.

**Comment by MoSheikh** [comment]
@simonplend Thank you, that's great. My mistake for missing that! I see that I add the custom error handler to a post-validation hook and override the response that way. 

Appreciate the help 👍

**Comment by simonplend** [comment]
@MoSheikh No problem, glad that helped!

**Comment by melroy89** [comment]
To actually give the correct answer, since creating a new error object is not required:

```
fastify.setErrorHandler((err, req, reply) => {
    req.log.error({ err })
    if (err.validation) {
      // Override default validation 400 status code to 422
      err.statusCode = 422
      reply.send(err)
    }
  })
  // .....
}
```

I thought setting `reply.status(422)` would do the trick, but no... In fact it doesn't matter what I set as `reply.status` or `reply.code`, the final HTTP status code seems to be coming from `statusCode` number from the error object, very strange indeed.

Could this be a bug? I dunno.. I think so.

**Comment by simonplend** [comment]
@melroy89

> To actually give the correct answer, since creating a new error object is not required:

It's not *required* to create a new error object, but if you wanted to send a different error message then you would probably want to do this.

> I thought setting reply.status(422) would do the trick, but no... In fact it doesn't matter what I set as reply.status or reply.code, the final HTTP status code seems to be coming from statusCode number from the error object, very strange indeed.
>
> Could this be a bug? I dunno.. I think so.

I don't believe this is a bug, but expected behaviour. FWIW, I seem to recall Express behaves similarly too when serializing an error object into a response.

If you prefer to call `reply.status()` instead, perhaps you could `delete err.statusCode` first. Otherwise you'd need to approach it in the way you described, or create a new error object which reuses the original error's error message e.g. `new Error(err.message)`.
