### ISSUE TITLE
Question fastify-cors Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by ramonmulia** [fastify/help#619]
Hey,

I'm using `fastify-cors` to set cors, so I have a configuration like this: 

```javascript
fastify.register(require('fastify-cors'), {
    origin: '*',
    methods: ['GET', 'POST']
  })
fastify.get('/api/execute', (req, reply) => {
    reply.send({ hello: 'world' })
  })
fastify.post('/api/execute', { schema }, function (request, reply) {
  reply.raw.setHeader('Access-Control-Allow-Origin', '*')
 ....
}
```

for the GET calls it works just fine without setting `reply.raw.setHeader('Access-Control-Allow-Origin', '*')` why do I need to set this for the POST calls?

as the `origin` option says: `origin: Configures the Access-Control-Allow-Origin CORS header.` is it suppose to add it on response header?

**Comment by nlapshin** [comment]
Could you send request example? Also, send fastify + fastify-cors version if you can.

'methods' options only affect to preflight request.

**Comment by climba03003** [comment]
I have see the usage in the PR linked. The behavior is expected and correct.

Since `fastify-cors` is using `reply.header` and headers it set will be cached but not directly written to `reply.raw` unless you use the normal flow like `reply.send`.

I would recommend you to change all `reply.raw.write` and `reply.raw.send` into `reply.send`. Then `fastify-cors` will work as expected.
