### ISSUE TITLE
fastify-jwt: decorating jwtVerify, why so complex?

### ISSUE THREAD

**Issue by jutunen** [fastify/help#637]
**fastify-jwt documentation says:**
_However, most of the time we want to protect only some of the routes in our application. To achieve this you can wrap your authentication logic into a plugin like_
```
const fp = require("fastify-plugin")

module.exports = fp(async function(fastify, opts) {
  fastify.register(require("fastify-jwt"), {
    secret: "supersecret"
  })

  fastify.decorate("authenticate", async function(request, reply) {
    try {
      await request.jwtVerify()
    } catch (err) {
      reply.send(err)
    }
  })
})
```
**Why should the decorator be wrapped into a plugin?**
Is it an antipattern to decorate jwtVerify straight away at the server entry point like this:
```
const fastify = require("fastify")({
    logger: true,
});

fastify.register(require("fastify-jwt"), {
    secret: "supersecretsecret",
});

fastify.register(require("./route"));

fastify.decorate("authenticate", async function(req, reply) {
    try {
      await req.jwtVerify()
    } catch (err) {
      reply.send(err)
    }
  })

const start = async () => {
    try {
        await fastify.listen(3333);
    } catch (err) {
        fastify.log.error(err);
        process.exit(1);
    }
};
start();
```

thanks and regards,
Jussi

**Comment by mcollina** [comment]
It is complex because applications are complex and have multiple concerns. I have found that most docs and tutorial focus on the most simple case that you never want to run in production - completely omitting how the software will run together with the other pieces of technologies in your system.

Wrapping such concerns in their own plugin will scale as you project become more complex.
