### ISSUE TITLE
Manage HTTP 504 Gateway Timeout

### ISSUE THREAD

**Issue by simon-tannai** [fastify/help#657]
## 💬  Manage HTTP 504 Gateway Timeout

I'm invoking an AWS Lambda to do some process on a video.
This invokation take few minutes, causing an HTTP 504 error to the client side (Axios without timeout limitation).

The process on the Lambda is not killed, it's running well.

I have increase the timeout limitation into Fastify server configuration but it does not change anything

```js
{
  connectionTimeout: 300000,
  keepAliveTimeout: 300000,
  requestTimeout: 300000,
  http2SessionTimeout: 300000,
}
````

How can I manage this HTTP 504 error ?

## Your Environment

- *node version*: 14
- *fastify version*: 3.27.1
- *os*: Docker

**Comment by climba03003** [comment]
Do not know how you configure the `aws` infrastructure, but I assume it is the problem of `aws` instead of `fastify`.

The default maximum timeout of `aws lambda` is 30 seconds.
https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html

If you believe it is the problem of `fastify`. Can you provide a repro without deploying to `aws`?

**Comment by simon-tannai** [comment]
Thanks @climba03003 for your anwser.

After new investigations, I found the issue. I was not coming from Fastify but from my hosting provider (Clever Cloud). 
HTTP 504 Gateway Timeout seems to usally come from hosting provider / network configuration instead of server himself :)
