### ISSUE TITLE
How can I stop processing the request without leaking anything

### ISSUE THREAD

**Issue by CristiTeo** [fastify/help#753]
## 💬  Question here 
I am currently implementing a plugin to slow down the response.
Because I am slowing down the response, the request can be aborted, and it means that the server is still trying to process the response, but no one is waiting for it.
How can I stop processing it without leaking anything?

**Comment by mcollina** [comment]
Unfortunately, it will still hold resources until the socket is open.

**Comment by simoneb** [comment]
@mcollina I think the question is, if we know the client has disconnected, what's the best way to short circuit the request/response cycle within fastify to avoid doing work that we know doesn't need to be done since the client has already disconnected? 

Imagine we realize that the client has disconnected from within a onRequest hook, what's the best way to short circuit it so we don't even hit the route handler?

**Comment by mcollina** [comment]
That's a more interesting question to answer. I don't think we are short-circuiting now, but it would be amazing if we did.

**Comment by simoneb** [comment]
So I guess sending an empty reply from within the hook so no further processing is done is the most reasonable option at the current time?

**Comment by mcollina** [comment]
> So I guess sending an empty reply from within the hook so no further processing is done is the most reasonable option at the current time?

Yes, that should already be working
