### ISSUE TITLE
why does eslint require await for synchronous request and reply methods in VS code?

### ISSUE THREAD

**Issue by budarin** [fastify/help#775]
## 💬  Question here 

here the code:
![code](https://user-images.githubusercontent.com/8055157/196453304-28c7a5e8-7da7-438a-a4de-b6e72f8e8701.png)

eslint error:
![image](https://user-images.githubusercontent.com/8055157/196453814-a50da9f6-44f9-4285-9bc0-c3feb6694487.png)

## Your Environment

- *node version*: 18
- *fastify version*: 4.9.2
- *os*: any
- VS Code: 1.72.2

**Comment by Uzlopak** [comment]
Seems to be, that typescript thinks that it is a promise and not a sync function. 

Can you provide a repo with that issue?

**Comment by budarin** [comment]
@Uzlopak here is [it](https://github.com/budarin/fastify-eslint-problem)

**Comment by Uzlopak** [comment]
LOL, that package has half of the npm registry as dependencies ;).

Ok it is because FastifyReply has a .then-method

https://github.com/fastify/fastify/blob/68914519a3fd65ce65ba8db8962940eecf7f0fc8/types/reply.d.ts#L63

so eslint assumes it is a a Promise. 

https://github.com/typescript-eslint/typescript-eslint/blob/0be356bae50156ba159c70d570b030e6d94afcb1/packages/eslint-plugin/src/rules/no-floating-promises.ts#L184

It is an issue of eslint and not of Fastify.

**Comment by budarin** [comment]
I wanted to keep the system in the state it is in for investigation :)

But they will rightly object to me that everything that has the 'then' method is a Promise and what should I do in this situation?

**Comment by Uzlopak** [comment]
You mean with "they" your colleagues?

Well sorry, but it is what it is. I dont know how we could fix it on our side to get that false positive fixed. It is an issue of eslint, as it is ducktyping it too wide. 

What you can do is to add a local patch and remove the then-method in reply.d.ts

**Comment by jsumners** [comment]
> everything that has the 'then' method is a Promise

Not so. Such things are [thennables](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#thenables).

As covered in https://github.com/fastify/fastify/issues/4246, it's out of our control.

**Comment by budarin** [comment]
ok, I created an issue in eslint
