### ISSUE TITLE
Is fastify-response-validation necessary?

### ISSUE THREAD

**Issue by BennyH26** [fastify/help#786]
Is the library fastify-response-validation necessary necessary for response validation? I thought this came out of the box.

**Comment by Eomm** [comment]
Request validation is provided out of the box.

Response validation is your choice: the server/developer implements the business logic and returns the data.
I validate the data when I store it in my system, so I don't need to validate the output values because it adds overhead.

I don't know your use case, but that plugin is an opt-in solution because all developers need to validate input, not everybody needs to validate output

**Comment by Eomm** [comment]
At the moment: yes, it is. Few keywords do the validation (oneOf, anyOf, required) as side effect, but there is an open discussion here about this topic: https://github.com/fastify/fast-json-stringify/discussions/532

We are going to normalize it and provide a more consistent API
