### ISSUE TITLE
Response time

### ISSUE THREAD

**Issue by divyanagrath** [fastify/help#83]
Is there a way to log API response time?

**Comment by mandaputtra** [comment]
Yeah, actually that isn't exposed. Just tried that so the best way for you its calculate it yourself on `onRequest` and `onResponse`

```js
function now () {
  var ts = process.hrtime()
  return (ts[0] * 1e3) + (ts[1] / 1e6)
}

let executionTime = 0
fastify.addHook('onRequest', (request, reply, next) => {
  executionTime = now()
  next()
})

fastify.addHook('onResponse', function(req, reply, next) {
  let responseTime = now() - executionTime // in ms
  console.log(responseTime) // this is the response time, almost same as fastity responseTime
  next()
})
```

Yes instead of `console.log` you can write your logging somewhere else using `fs.writeStream` module. But actually. if you just needed logging why not use `pm2` or what else tools that already had logging system? and just turn on `logger: true` in case you need something you could just make another app, that crawls the log file for you and give you report

**Comment by Eomm** [comment]
Beware that on each request the execution time is updated, so that snippet could not count the right time.

> Instead of console, is there a way I can write this info in a file?

You can customize the logging with [pino-multi-stream](https://github.com/pinojs/pino-multi-stream) or use directly [pino-tee](https://github.com/pinojs/pino-tee)

> Or can I access these params like responseTime, time, statusCode?

I don't think you can access timings, I looked the code a bit and those infos are hidden in a Symbol.
What do you would like to do?

**Comment by divyanagrath** [comment]
Thanks @mandaputtra, using your way of calculating responseTime.

**Comment by DRoet** [comment]
FYI for the next person that stumbles across this thread, you can now also call [reply.getResponseTime()](https://www.fastify.io/docs/latest/Reply/#getresponsetime) in the `onResponse` hook

**Comment by matt-greenfield-15** [comment]
`getResponseTime()` has now been deprecated.
You should use [reply.elapsedTime](https://fastify.dev/docs/latest/Reference/Reply/#elapsedtime) 

Thanks @DRoet for the original answer
