### ISSUE TITLE
Help (node:14589) [FSTDEP012] FastifyDeprecation - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by venkateshb-icanio** [fastify/help#833]
(node:14589) [FSTDEP012] FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in `fastify@5`.
Segmentation fault (core dumped)
error Command failed with exit code 139.

If I did any db queries using prisma model , It is showing this error.

My Environment

Node version v18.13.0

package.json
 "@fastify/cors": "^8.1.0",
    "@fastify/helmet": "^9.1.0",
    "@fastify/routes": "^5.0.0",
    "@fastify/swagger": "^7.4.1",
    "fastify": "^4.2.1",
    "fastify-plugin": "^4.0.0",

**Comment by Uzlopak** [comment]
Code 139 is a Linux Error and Segmentation fault means that you have memory issues. E.g. you run your code in docker and assigned not enough RAM. So while prisma spins up and allocates memory, the memory is full and Linux terminates the docker process.

Your issue did not contain enough information to determine any bug or issue in fastify.

**Comment by wsilva** [comment]
Hello @venkateshb-icanio.

Were you able to solve it? Or worked on it in another way?
Do you have more information about when (in which conditions) thi error 139 happens?

I am also facing an issue with an application that crashes with error 139 and it is running inside a containerd container.

It happens when we are trying to fetch some data  from database using typeorm.

Any help or update are welcome
🙇

**Comment by climba03003** [comment]
If you need further helps, please open another issue with reproducible code snippets.
In your case, if it related to docker, `Dockerfile` would be helpful.
