### ISSUE TITLE
Is it possible to get typed responses using Typescript?

### ISSUE THREAD

**Issue by Qocotzxin** [fastify/help#840]
## 💬  Question here 

I'm wondering if it's possible to get type checking for the reply, no matter if it's an error or a successful response. As per issues [#125](https://github.com/fastify/help/issues/125) this was possible in V3 by using generics. But now using generic with send throws an error. Some examples:

```ts
      return rep.status(500).send<Response>({
        ok: false,
        data: { token: null },
        message: "Access Token creation failed.",
      });

Typescript Error: Expected 0 type arguments, but got 1.
````

Another option is to extend the FastifyReply interface:

```
export type FastifyCustomReply<T> = FastifyReply<
  RawServerDefault,
  RawRequestDefaultExpression<RawServerDefault>,
  RawReplyDefaultExpression<RawServerDefault>,
  RouteGenericInterface,
  ContextConfigDefault,
  FastifySchema,
  JsonSchemaToTsProvider,
  T
>;
```

This solves the problem partially, first because I'm overriding the Raw type which is not ideal and also because now this works:

```
      return rep.send({
        ok: false,
        data: {  }, // TS correctly points that token field is missing here.
        message: "Access Token creation failed.",
      });
```

But this doesn't:

```
      return rep.status(500).send({
        ok: false,
        data: {  }, // No typings here.
        message: "Access Token creation failed.",
      });
```

So in order to make it work as expected I need to override every single chainable method:

```
export interface FastifyCustomReply<T> extends FastifyReply {
    send(payload?: T): FastifyReply;
    code(statusCode: number): FastifyCustomReply<T>;
    status(statusCode: number): FastifyCustomReply<T>;
    header(key: string, value: any): FastifyCustomReply<T>;
    headers(values: { [key: string]: any }): FastifyCustomReply<T>;
}
```

This actually makes the trick, but it seems quite complex, ideally I should be able to pass the type to Reply one time, or at least to pass the generic to the function I'm calling (like issue #125) to get the correct types to send my response.

I couldn't find anything in the docs pointing me in the right direction to accomplish this. Right now I'm using` json-schema-to-ts` to convert my schemas to TS types mostly because withTypeProvider won't correctly type functions that are declared in different files.

## Your Environment

- *node version*: 18.14.1
- *fastify version*: 4.13.0
- *os*: Ventura 13.2.1

**Comment by mcollina** [comment]
Thanks for reporting! It seems you have a project layout issue that prevents you to use `withTypeProvider`. I think the _preferred_ way to reach your goal is to set that up correctly.

Can you provide a repository with the error?

**Comment by Qocotzxin** [comment]
Yeah, I'm pretty sure I'm missing something here, thanks for the quick reply and this great project!

Here is a Stackblitz repro (it's using Node 16 instead of 18, but I believe for this specific issue it shouldn't matter):

https://stackblitz.com/edit/fastify-j65bsr?file=src/index.ts

**Comment by mcollina** [comment]
Can you put it on github so it's easy to clone? Unfortunately stackblitz is _not_ node.js (despite what they say).

**Comment by Qocotzxin** [comment]
Sure: https://github.com/Qocotzxin/1on1-api

**Comment by mcollina** [comment]
I did take a look. You are right that this is not supported, I thought it was!

@sinclairzx81 @fastify/typescript do you think responses could be supported as well?

**Comment by sinclairzx81** [comment]
@mcollina Hi. Typed responses should be supported with type providers (added on https://github.com/fastify/fastify/pull/3524). The following creates some literal string responses for `200`, `404` and `500` status codes. Note the red underline on the `send()` parameter where it's catching an invalid response string.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYCEIA82YAKUEAbsACYZRwC+cAZiSHAOQACDAhgM4zANUAehjoMAWjAlyVKONGYARnlYBYAFChIsRCjF1GzNux7AAdgGMANl2BQRY5bjWbw0eADFe-QYYgtWbj4BVBcNL2DBAAoASgA6AHdgGAALAgxiMkpqAB50nHwxTJlqAD5YuMg+KNYRDD5WABpEDTg4HgsUjBAuAC4W9Ta25QpUfvS4gHlFACsMCxgohFahttxxsTiAZRgocwBzWMaV1bG9TDiAOQBXEEVqWJO6GOPBoah6yDMeDH7lt9WACYAAzAjYXAAyyWoXCsNVSwB4cERcC4cBBwLgHx4Xx+rBeTzaABZgUTwRg4lCYDC4awEUiUWiSUSsZ8IN8MPjXqs2gBWUHkynQqCw+EpFGMuD8zHY3GcgkAugrWgaWjNKIfACOzQ+YCsqBicAAvKUBhpzeoVrr9XEfmYKDVzKRYZRxLL2T9xHw9mZ9vi4EIhHAzBB4GjnVZKKycR6MABCOCqmJAA)

![image](https://user-images.githubusercontent.com/3048342/221210826-07236f08-3cf1-4e42-96a9-418efc04471f.png)

> Quick Note: On the 4.0 release, there was a limitation where TS couldn't quite narrow for the response type based on the status code. This was due to the 4.0 definition for the response object (and making changes here would have resulted in a breaking change to the original generics). However this should be considered in future (perhaps the next major semver). A little bit of information on this exists https://github.com/fastify/fastify/pull/3524#issuecomment-991913407 and https://github.com/fastify/fastify/pull/3524#issuecomment-991938027 for reference.

---

@Qocotzxin Hi!, had a quick look at the repo (thanks for that). The reason the types are not flowing is due to the `responseSchema` structure not being passed into external function (so the provider loses track of the type). I've setup a quick example of how to fix (which is to inline the schema + route in the same place) so may require a small refactor (but the code should simplify quite a bit). I've left a few comments in there to help.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgKQM4QHYGUDGALAUxAEMAVCU1ABSggDdgATAqOAXzgDNaQ4ByAAKdiqGME4BPAPQwJYAgFowtBsygKAVugwLU+IsQUwIR1HwCwAKFCRYcAGIixkrj37DR4iRctWpUhUCg4JDQsPCIyKiQvyk4AEkYPlQ4CABrOGM4EHoCTLxgFL1CEkyIOGIMCBhCVk5gABsCADo4ADlqggAuOAkIAFdUjAaJOAwCAkYyuFi4AgAPW3gawrhRKH6cGH6oPMqpkVRgAHMMOGBl8pq82n6YAhTd1EgMVDzigwAaGct-fLzlPQmCw4AB3RoNCp3CAkMQ4YgNEZweGIhw8XAlYgAHlIAD4uNBegNWrFomTyRTKQorFYFktkZhRHAAEoPF5vUhyPIAXkQVjgmS5PQARBAAEYaAhbYWfflwXYAR36wF2jB6AG1RWkZXBhYxiDBiDrhSAHqhiMcCMKALqyywCwHyWDAB49BBygXpN0egWC+QisUQCBNSoyn0C5h6KDAMBiTBdcO+4UAQTggeDlTgdAR-TyWSVwBwaSRzHuUBAwHG504-1SToNwEwYJEa02ODNnH6kMJVRgzTD9t9bDtvrg+sN3sHo9k-t14sl0pHo-lBALqo1wuMaQIGBtS9HkZw0djjYwIuTZ3nUuWeANDIwhsrKWuK6VD3uU3HxDgAApxBUMAkABKft919R0WDEV0+SnZctx3SdlzgoVdXWStjgHJDRwwLsGmIMUmh6GANgIMCkMPY84zPRMkOFUhCDKbczktcYoANSY01GUhwQaRtfx7XDq1reCzhwAYGimXs0zyFiWHYxgQMwrDh0TFTYLU0dTVQc1LUQ5DZ2FNCMAwsixweI8YyohNYNHFM1jwaB4C0nS81veBAVUB5zgwThoFhU8KkDO5ayedkWiUgUNPYO0OBbMTXhgABuGlfjiKl0oy6JZgAdUIM5QWjMRjPlAZ7hScEajgDzgSgVBvguZI4GOIMpiySteKrF8PhIWZ9hKu48gaCBjkLbza3NU0qrw9tWno1ZCAaMBn3KDy83KUgsFrWYZy84hdgZKBdi2ACDkRCBQRSStOBYHd22mR0LXY-JbmOPBvKybaGNue44FvDBGCaKBZoY3yzvBYrVhfI6YVNf6OJsJpYcNKi7T+dAiUGEhRnGDjv12YQtkJSspuIdtUGaWZMqp6mgisRxPEkH8QIqvBOXkGggTULE0EwDEDHISgOc8qBcSZ5pLRgH8+CkPhvndQduuIPSBVCxluhgpCACYAAZtZ6VlnjVtmCB9Ng5TNyxh1-RVvieIC4G5fF5blP5jEYCAejwGAYCWrp-BGmp+jFZoxJAKQAEUIDEmAAC95krKQAEZMEThRiDAYApAI8UpBIUQWCkVAoBwKR4uI4NAdQKRiDuPBmhgVAAGIABlE+1hRm4AVk1n4BTlJ5mjef6fyQV2uV0YhrpXQ3XjyH9iNGfBKhG4q2owbNeKmDfc1QICfS9TISO+H0vzdRiEP4RPNYAZj4aLe99ZyLXVvg7-NvfLY-qwgA)

<details>
<summary>
Expand for Example
</summary>

```typescript
import { JsonSchemaToTsProvider } from '@fastify/type-provider-json-schema-to-ts'
import Fastify from 'fastify'

//-----------------------------------------------------------------------
// It's ok to move this schema to another file. Note: you only need to 
// export this structure and assign it to the routes response schema, 
// the provider will automatically call FromSchema<T> for you. 
//-----------------------------------------------------------------------

export const ResponseType = {
  type: "object",
  required: ["ok", "data", "message"],
  properties: {
    ok: {
      type: "boolean",
      description:
        "A boolan value to quickly determine if the operation was successful or not.",
    },
    data: {
      type: "object",
      required: ["token"],
      description: "An object that contains the requested data (if any).",
      properties: {
        token: {
          type: "string",
          nullable: true,
          description:
            "The token generated by Twilio (or null if the token could not be generated).",
        },
      },
    },
    message: {
      type: "string",
      description:
        "A short message that provides information about the response.",
    },
  },
} as const;

// ------------------------------------------------------------------
// When writing routes with providers, it's good to inline the schema
// and route logic in the same place. This helps to prove to TS the 
// types are correct and allows inference to propagate through into 
// the route handler. The following is the recommended implementation,
// so you may need a refactor in places.
// ------------------------------------------------------------------
Fastify().withTypeProvider<JsonSchemaToTsProvider>().get('/', {
  schema: {
    response: {
      200: ResponseType
    }
  }
}, (req, res) => {

  // todo: https://github.com/Qocotzxin/1on1-api/blob/master/src/controllers/auth.ts#L10-L52 
  
  res.send({ // type-safe response (try changing to invalid values)
    ok: true, 
    data: { token: '123' }, 
    message: '' 
  })
})
```

</details>

Hope this helps!
S

**Comment by Qocotzxin** [comment]
@sinclairzx81 @mcollina thank you very much for taking a deeper look into this issue, really appreciate it. After making this changes it actually worked. I tried using the inline function before but it seems importing the whole response schema won't work, which is kind of confusing to be honest (it would be nice to make it more clear in documentation) but it does the trick.

Now, I would still consider the possibility of using generics if possible (seems hard to accomplish according to the comments) because it allows replacing inline functions and using a modular approach. That way you can keep your routes file clean and readable. I guess for now I can get around this by generating good documentation (I saw there is a swagger plugin, thanks for that!) but there is a clear benefit on adding generics (ideally to the Fastify instance imo so you don't need to define them each time you call send/code/etc).

I will close the issue now and, again, thanks a lot for the help!

**Comment by samrocksc** [comment]
Hmmm, in my case i'm trying to make schema driven design choices by having openapi-typescript generate my types, I'm trying to avoid having to write the whole schema over again

**Comment by sinclairzx81** [comment]
@samrocksc If it's helpful, give this tool a try https://sinclairzx81.github.io/typebox-workbench/. It will generate both JSON Schema and TypeBox types from TS types and perhaps help to accelerate conversion between type representations (which can be a bit painful)

Sometimes it's helpful to model types in TS first (given the terse syntax) then convert that out to other things.
