### ISSUE TITLE
Getting InvalidState with FastifyoAuth

### ISSUE THREAD

**Issue by TMachadoDev** [fastify/help#974]
In the callback auth, im getting an error message saying invalid state

server.ts

```js

import fastify from "fastify";
import { authRoutes } from "./routes/auth.routes";
import { FastifyInstance } from "fastify";
import oauthPlugin from "@fastify/oauth2";
const app: FastifyInstance = fastify({ logger: true });
import dotenv from "dotenv";
dotenv.config();
app.register(authRoutes, {
  prefix: "/auth",
});

app.register(oauthPlugin, {
  name: "discordOAuth2",
  credentials: {
    client: {
      id: process.env.DISCORD_ID as string,
      secret: process.env.DISCORD_SECRET as string,
    },
    auth: oauthPlugin.DISCORD_CONFIGURATION,
  },
  scope: ["identify"],
  // register a fastify url to start the redirect flow
  startRedirectPath: "/login/discord",
  // facebook redirect here after the user login
  callbackUri: "http://localhost:3100/auth/discord/callback",
  
});

app.listen(
  {
    port: 3100,
  },
  () => console.log("Server Running Sucessfully")
);
```

auth.routes.ts

```js
import { FastifyInstance } from "fastify";

export async function authRoutes(fastify: FastifyInstance) {
  fastify.get("/discord/callback", async function (request, reply) {
    try {
      // the response will have the `code`
      const token =
        await this.discordOAuth2.getAccessTokenFromAuthorizationCodeFlow(
          request
        );

      console.log(token);

      // in async handler it is possible to just return the payload!
      return reply.send(token);
    } catch (error) {
      return reply.send(error);
    }
  });
}

```

**Comment by giovanniruzzi** [comment]
Hello @TMachadoDev, 

I've looked into the problem you're dealing with. It seems that the instructions on [fastify-oauth2](https://github.com/fastify/fastify-oauth2) are unclear about the steps for setting up oauth2. From your code, it looks like there is only one endpoint `/discord/callback`. If you tried this from the discord developer portal, this could be why you ended up with an invalid state. 

After commits [bff756b](https://github.com/fastify/fastify-oauth2/commit/bff756b456cbb769080631af2beb85671ff4c79c) and [7709f45](https://github.com/fastify/fastify-oauth2/commit/7709f45a7ac26589532cf47072110521119c1331), authentication needs to take place via an authorization URI (generateAuthorizationUri). This means you need to create a new endpoint (eg. `/external`) and use your web browser for this step because it's crucial to set up a browser cookie. This new endpoint instantly leads you to the sign-in page so you can approve it. After this, you'll be led back to the `/discord/callback` endpoint. At this point, the state gets passed in the querystring and this is checked by the cookie. 

So, in short, here's what you need to do:
1. Modify your `auth.routes.ts`
```typescript
import { FastifyInstance } from "fastify";

export async function authRoutes(fastify: FastifyInstance) {
  fastify.get("/discord/callback", async function (request, reply) {
    try {
      const token =
        await this.discordOAuth2.getAccessTokenFromAuthorizationCodeFlow(
          request
        );
      return reply.send(token);
    } catch (error) {
      return reply.send(error);
    }
  });

  fastify.get(
    "/external",
    {},
    (req, reply) => {
      fastify.discordOAuth2.generateAuthorizationUri(
        req,
        reply,
        (err, authorizationEndpoint) => {
          reply.redirect(authorizationEndpoint)
        }
      );
    }
  );
}
```
2. Use your browser to connect to this new endpoint 
3. Approve your request directly on discord
4. Receive the token.

For reference: please have a look at the full example[fastify-discord-oauth2-example](https://github.com/giovanniruzzi/fastify-discord-oauth2-example)

**Comment by TMachadoDev** [comment]
Thank you so much, that worked so well, you managed to explain me  everything with detail, I could not be more grateful @giovanniruzzi.

**Comment by mcollina** [comment]
@giovanniruzzi could you send that PR?

**Comment by giovanniruzzi** [comment]
Yes, give me some more days, I'll create the PR

**Comment by giovanniruzzi** [comment]
@mcollina done. Sorry for the long wait 😞

**Comment by TMachadoDev** [comment]
Thank you so much @giovanniruzzi, i really did appreciate all your effort and work into this issue.
